Repository primesearch/mfakto, pull requests merged in 2025-09, with the labels that each got.

#20 Use OpenCL 2.0 APIs when possible
  src/mfakto.cpp
  src/my_types.h
  todo.txt
Labels: enhancement

#28 clean up program output and changelog
  .gitignore
  Changelog-mfakto.txt
  README.txt
  src/Makefile
  src/output.c
  src/params.h
Labels: documentation, enhancement

#31 re-organize mfakto.ini to be more user-friendly
  Changelog-mfakto.txt
  src/mfakto.ini
Labels: enhancement

#32 remove temporary step to update Homebrew
  .github/workflows/ci.yml
Labels: bug

#33 integrate the vcpkg package manager
  .github/workflows/ci.yml
  .gitignore
  Changelog-mfakto.txt
  README.txt
  mfaktoVS12.vcxproj
  mfaktoVS12.vcxproj.filters
  src/mfaktc.c
  src/mfakto.ini
  src/params.h
  vcpkg-configuration.json
  vcpkg.json
Labels: enhancement

#34 bump vcpkg to version 2025.09.17
  Changelog-mfakto.txt
  README.txt
  vcpkg-configuration.json
Labels: documentation, enhancement

#35 JSON checksum from mfaktc
  Changelog-mfakto.txt
  mfaktoVS12.vcxproj
  mfaktoVS12.vcxproj.filters
  src/Makefile
  src/checkpoint.c
  src/checkpoint.h
  src/crc.c
  src/crc.h
  src/mfaktc.c
  src/my_types.h
  src/output.c
  src/output.h
  src/params.h
Labels: enhancement

#37 bump version to `0.16-beta.3`
  .gitignore
  README.txt
  mfaktoVS12.vcxproj
  src/barrett.cl
  src/barrett15.cl
  src/common.cl
  src/datatypes.h
  src/gpusieve.cl
  src/mfakto_Kernels.cl
  src/montgomery.cl
  src/mul24.cl
  src/params.h
Labels: enhancement
